[package]
name = "builtin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
smallvec="1.8.0"
syn="1.0.91"
quote = "1.0.18"
proc-macro2="1.0.37"