[package]
name = "cli"
version = "0.4.0-alpha.28"
edition = "2021"
publish = false

[dependencies]
xshell = "0.2.3"
clap = {version = "4.5.4", features = ["cargo", "derive"] }
anyhow = "1.0" 
fs_extra = "1.3.0"
notify-debouncer-mini = "0.4.1"
gitignore = "1.0.8"
