[env]
CARGO_WORKSPACE_DIR = {value = "", relative = true}

[alias]
run-wasm = "run --package ribir-cli -- run-wasm --template ./tools/cli/template"
bundle = "run --package ribir-cli -- bundle"
ci = ["-Zscript", "tools/ci.rs"]
