[package]
name = "ribir-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
comrak = "0.31"
