[package]
authors = ["Adoo <Adoo@outlook.com>"]
edition = "2021"
name = "ribir_macros"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
ahash = "0.8.3"
bitflags = "1.3.2"
lazy_static = "1.4.0"
proc-macro2 = "1.0.36"
quote = "1.0.16"
ribir_builtin = {path = "./builtin"}
ribir_painter = {path = "../painter"}
smallvec = "1.8.0"

[dev-dependencies]
ribir = {path = "../ribir"}
ribir_core = {path = "../core"}
trybuild = "1.0.77"
winit = "0.28.1"

[build-dependencies]
ribir_builtin = {path = "./builtin"}

[dependencies.syn]
features = ["visit-mut", "full", "extra-traits"]
version = "1.0.83"
