[package]
categories = ["gui"]
description = "Ribir is a framework for building modern native/wasm cross-platform user interface applications."
documentation = "https://ribir.org/docs"
edition = "2021"
homepage = "https://ribir.org"
keywords = ["gui", "ui", "declarative", "compose-ui"]
license = "MIT"
name = "ribir_painter"
readme = "README.md"
repository = "https://github.com/RibirX/Ribir/algo"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.0"
euclid = "0.22.6"
log = "0.4.17"
lyon_algorithms = "1.0.1"
lyon_tessellation = {version = "1.0.1", features = ["serialization"]}
palette = {version = "0.6.1", features = ["serializing"]}
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_geometry = {path = "../geometry"}
ribir_text = {path = "../text", version = "0.0.0"}
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0.82"
usvg = {version = "0.29.0"}
rctree ="0.5.0"
<<<<<<< HEAD
=======
bitflags-serde-legacy = "0.1.0"
>>>>>>> a0665d2f38fb666548d265846d0b59384ea22772
