[package]
edition = "2021"
name = "ribir_text"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ribir_algo = {path = "../algo"}
derive_more = "0.99.17"
fontdb = "0.7.0"
log = "0.4.14"
lyon_path = "1.0.1"
ordered-float = "2.10.0"
rustybuzz = "0.5.0"
ttf-parser = "0.15.0"
unicode-bidi = "0.3.7"
unicode-script = "0.5.4"
unicode-segmentation = "1.9.0"
