on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 14 * * 2" # runs every Tuesday at 14:00 UTC
permissions:
  contents: write
name: "Alpha Version"
jobs:
  master_check:
    runs-on: ubuntu-latest
    steps:
      - name: Master check
        if: github.ref != 'refs/heads/master'
        run: |
            echo "Alpha version can be released only from master branch"
            exit 1
  commit_check:
    needs: master_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: |
          new_commit=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline | wc -l)
          if [ $new_commit -eq 0 ]; then
            echo "No new commits since last version"
            exit 1
          fi
  call-workflow-passing-data:
    needs: commit_check
    uses: RibirX/rclog/.github/workflows/release-version.yml@main
    with:
      level: 'alpha'
      ref: ${{ github.ref }}
      merge_changelog: false
      toolchain: stable
    secrets:
      CRATE_RELEASE_TOKEN: ${{ secrets.CRATE_RELEASE_TOKEN }}
      GITHUB_RELEASE_TOKEN: ${{ secrets.RIBIR_RELEASE }}